version: "3.1"
services:
  www:
    build:
      context: ./php/docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php/code:/var/www/html/
    networks:
      - default
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crm_app
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/dump:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    networks:
      - default
