version: "3.1"
services:
  www:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html/
    networks:
      - default
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crm_app
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
    networks:
      - default
